id: P006909
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:08.749882
source_metadata:
  id: bdr:W1PD152284
  title: རེབ་གོང་ཆོས་འབྱུང་གདན་ས་གསུམ་གྱི་གདན་རབས།
  author: ''
  volumes:
    52a9dcad349647e2b121c7cfba203cf7:
      image_group_id: I2PD18999
      title: ''
      volume_number: 1
      total_pages: 358
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
