id: I41AA50A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:22:37+00:00'
last_modified: '2022-06-08T09:33:21.568588+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD152284
  title: རེབ་གོང་ཆོས་འབྱུང་གདན་ས་གསུམ་གྱི་གདན་རབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2194':
      image_group_id: I2PD18999
      title: ''
      total_pages: 358
      order: 1
      base_file: 2194.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
